# dvc.yaml
stages:
  get_data:
    cmd: python scripts/data.py
    deps:
      - scripts/data.py
    params:
      - index_col
      - retrain #: true
    outs:
      - data/initial_data.csv
  fit_model:
    cmd: python scripts/fit.py
    deps:
      - data/initial_data.csv
      - scripts/fit.py
    params:
      - index_col
      - target_col
      - one_hot_drop
      - auto_class_weights
      - retrain #: true
    outs:
      - models/fitted_model.pkl
  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - models/fitted_model.pkl
      - scripts/evaluate.py
    params:
      - index_col
      - target_col
      - n_splits
      - n_jobs
      - metrics
      - retrain #: true
     
    outs:
      - cv_results/cv_res.json
# ---------------------------------------------------------------------------------
  # /home/mle-user/mle_projects/mle-dvc/Progect1/mle-project-sprint-1-v001/part2_dvc/models
  
  get_data_progect1:
    cmd: python Progect1/mle-project-sprint-1-v001/part2_dvc/scripts/data_estate.py
    deps:
      - Progect1/mle-project-sprint-1-v001/part2_dvc/scripts/data_estate.py
    params:
      - Progect1/mle-project-sprint-1-v001/params.yaml:
        - data.retrain           # пример параметра, можете убрать, если нет параметров
    outs:
      - Progect1/mle-project-sprint-1-v001/part2_dvc/data #/clean_data.csv

  fit_progect1:
    cmd: python Progect1/mle-project-sprint-1-v001/part2_dvc/scripts/fit_estate.py
    deps:
      - Progect1/mle-project-sprint-1-v001/part2_dvc/scripts/fit_estate.py
      - Progect1/mle-project-sprint-1-v001/part2_dvc/data
    params:
      - Progect1/mle-project-sprint-1-v001/params.yaml:
        - train.iterations
        - train.test_size
        - train.random_state
    outs:
      - Progect1/mle-project-sprint-1-v001/part2_dvc/models/price_predictor_model.pkl

  evaluate_progect1:
    cmd: python Progect1/mle-project-sprint-1-v001/part2_dvc/scripts/evaluate_estate.py
    deps:
      - Progect1/mle-project-sprint-1-v001/part2_dvc/scripts/evaluate_estate.py
      - Progect1/mle-project-sprint-1-v001/part2_dvc/models/price_predictor_model.pkl
    params:
      - Progect1/mle-project-sprint-1-v001/params.yaml:
        - evaluate.metrics              # пример параметра оценки (метрика качества)
    outs:
      - Progect1/mle-project-sprint-1-v001/part2_dvc/models/evaluation_results.json