# params.yaml
index_col: 'customer_id'
target_col: 'target'
one_hot_drop: 'if_binary'
auto_class_weights: 'Balanced'
n_splits: 5
metrics: ['f1', 'roc_auc']
n_jobs: -1
retrain: true
model:
  type: logistic_regression
  penalty: l2
  C: 1.0
  solver: liblinear