# params.yaml
index_col: 'customer_id'
target_col: 'target'
one_hot_drop: 'if_binary'
auto_class_weights: 'Balanced'
n_splits: 9
metrics: ['f1', 'roc_auc']
n_jobs: -1
retrain: True
model:
  C: 1.0
  penalty: l2
  solver: lbfgs
  max_iter: 1000
  random_state: 42
