data_table: real_estate_dataset_clean
# index_col: id

target: price
input_data: data/initial_data.csv
model_output: models/price_predictor_model.pkl

train:
  test_size: 0.2
  random_state: 42
  iterations: 1000
data:
  retrain: true
evaluate:
  metrics:
    - mae
    - r2
